### ISSUE TITLE
Get last row from SQL query

### ISSUE THREAD

**Issue by William-Krug** [McKynlee/FLUENT_spike#1]
The only way I can get my query to work is by having all rows populate.  Do you remember how to get just the last row as the payload when I `dispatch`?

Code:
![Screen Shot 2021-03-16 at 4 23 46 PM](https://user-images.githubusercontent.com/75000619/111381676-04cffd00-8674-11eb-8c75-b27199b9ca88.png)

**Comment by McKynlee** [comment]
Try `payload: mostRecent.data[mostRecent.data.length -1]` to narrow down to just the specific row

**Comment by William-Krug** [comment]
Yup, adding `.data` while referencing the index did the trick.  Thanks!
